version: "3.8"
services:
    web:
        build: ./src
        networks:
            backend:
                ipv4_address: 172.16.0.2

networks:
    backend:
        ipam:
            driver: default
            config:
                - subnet: "172.16.0.0/29"
